model_name_or_path: models/Qwen3-4B-Instruct-2507
adapter_name_or_path: outputs/extractor_qwen3_4b/train_v3_1_30k
template: qwen3_nothink
finetuning_type: lora
infer_backend: huggingface
trust_remote_code: true
flash_attn: sdpa
bf16: true
do_sample: false
temperature: 0.0
max_new_tokens: 4096
